fix: configurating serverless plugins for deploying app
YRAL375/nodejs-aws-fe pull request #1
Opened 2021-08-16 08:58 UTC by YRAL375

Automated configured s3/cloudfront resources:

-S3 link: http://my-second-app-rsv.s3-website-us-east-1.amazonaws.com/

-Cloudfront link: https://d3e2p0b38yuj3g.cloudfront.net/

2021-08-17 10:52 UTC, Frol8612 commented
plz, add link on manual deployment

2021-08-17 15:16 UTC, YRAL375 commented
> plz, add link on manual deployment s3/cloudfront

@Frol8612  Hi! I was working on the task2 in accordance with Evaluation Criteria for this task and manual deployment was destroyed regarding point 2 in the PREREQUISITES 2.2 https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task2-serve-spa-aws/task.md

![image](https://user-images.githubusercontent.com/46975490/129753090-ddeace09-cd34-4cc6-b4c2-e8c4d8a3d7e7.png)

2021-08-17 15:39 UTC, Frol8612 commented
Review the [video](https://www.youtube.com/watch?v=LTNDfy_td1w).  There, the author talks about deleting, and asks to do it after checking.  And also look at the discord about it more than once wrote.  And these are the steps of implementation, and the criteria for what to evaluate are lower.  And I see that you have coped with the task, and I am not planning to change my assessment.

2021-08-18 08:33 UTC, YRAL375 commented
> Hi!) Please, review the [video](https://www.youtube.com/watch?v=LTNDfy_td1w). There, the author asks remove after cross-check. Also look at Discord about it more than once wrote. These are the implementation steps, and the criteria for what to evaluate are located below. You did the task well and I set the maximum score.

Thank you for the assessment!) Yes, I saw this video, but after I completed the task and deleted manual deployment)

2021-08-18 08:39 UTC, Frol8612 commented
OK)

2021-08-18 13:46 UTC, manuminsk requested changes

2021-08-18 13:46 UTC, manuminsk commented on serverless-single-page-app-plugin/index.js
> +        const s3Bucket = this.serverless.variables.service.custom.s3Bucket;
@YRAL375 Looks like you should have errors, because serverless.yml contains property s3BucketName instead.

I guess 
`this.serverless.variables.service.custom.s3Bucket` should be raplaced with `this.serverless.variables.service.custom.s3BucketName`

2021-08-18 13:46 UTC, manuminsk commented on serverless.yml
> +    bucketName: my-second-app-rsv
@YRAL375 
Probably it will be better to make service name `my-first-rs-app` and the bucket name `my-second-app-rsv` equal

2021-08-19 07:43 UTC, YRAL375 commented on serverless-single-page-app-plugin/index.js
> +        const s3Bucket = this.serverless.variables.service.custom.s3Bucket;
> @YRAL375 Looks like you should have errors, because serverless.yml contains property s3BucketName instead.
> 
> I guess
> `this.serverless.variables.service.custom.s3Bucket` should be raplaced with `this.serverless.variables.service.custom.s3BucketName`

Thanks! A good catch!)

2021-08-19 08:11 UTC, manuminsk approved these changes

2021-08-30 07:45 UTC, merged